/** Canonical permission codes — keep in sync with backend PermissionCodes. */
export const Permissions = {
  CREATE_TASK: 'CREATE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  COMMENT_TASK: 'COMMENT_TASK',
  VIEW_OWN_TASKS: 'VIEW_OWN_TASKS',
  VIEW_SCOPED_TASKS: 'VIEW_SCOPED_TASKS',
  VIEW_COMPANY_TASKS: 'VIEW_COMPANY_TASKS',

  REQUEST_TASK_CLOSE: 'REQUEST_TASK_CLOSE',
  REQUEST_DUE_DATE_EXTENSION: 'REQUEST_DUE_DATE_EXTENSION',
  APPROVE_TASK_REQUEST: 'APPROVE_TASK_REQUEST',
  REJECT_TASK_REQUEST: 'REJECT_TASK_REQUEST',
  ARCHIVE_TASK: 'ARCHIVE_TASK',
  ISSUE_WARNING: 'ISSUE_WARNING',
  DELETE_WARNING: 'DELETE_WARNING',
  ISSUE_PENALTY: 'ISSUE_PENALTY',
  DELETE_PENALTY: 'DELETE_PENALTY',

  VIEW_EMPLOYEES: 'VIEW_EMPLOYEES',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  ENABLE_EMPLOYEE: 'ENABLE_EMPLOYEE',
  DISABLE_EMPLOYEE: 'DISABLE_EMPLOYEE',
  ASSIGN_ROLE: 'ASSIGN_ROLE',
  ASSIGN_TO_MANAGERS: 'ASSIGN_TO_MANAGERS',
  ASSIGN_OUTSIDE_SCOPE: 'ASSIGN_OUTSIDE_SCOPE',
  CREATE_EMPLOYEE_TYPE: 'CREATE_EMPLOYEE_TYPE',
  UPDATE_EMPLOYEE_TYPE: 'UPDATE_EMPLOYEE_TYPE',
  DELETE_EMPLOYEE_TYPE: 'DELETE_EMPLOYEE_TYPE',

  APPROVE_LEAVE: 'APPROVE_LEAVE',
  REJECT_LEAVE: 'REJECT_LEAVE',

  VIEW_SCOPED_REPORTS: 'VIEW_SCOPED_REPORTS',
  VIEW_COMPANY_REPORTS: 'VIEW_COMPANY_REPORTS',
  RECEIVE_ORG_ESCALATIONS: 'RECEIVE_ORG_ESCALATIONS',

  CREATE_AREA: 'CREATE_AREA',
  UPDATE_AREA: 'UPDATE_AREA',
  DELETE_AREA: 'DELETE_AREA',
  CREATE_BRANCH: 'CREATE_BRANCH',
  UPDATE_BRANCH: 'UPDATE_BRANCH',
  DELETE_BRANCH: 'DELETE_BRANCH',
  CREATE_DEPARTMENT: 'CREATE_DEPARTMENT',
  UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
  DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',
  CREATE_PERMISSION: 'CREATE_PERMISSION',
} as const;

export type PermissionCode = (typeof Permissions)[keyof typeof Permissions];
