//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMangment.Utilities.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskNotifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskNotifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskMangment.Utilities.Localization.Resources.TaskNotification", typeof(TaskNotification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the task {0} has been closed according to request.
        /// </summary>
        internal static string CLOSEAPPROVED {
            get {
                return ResourceManager.GetString("CLOSEAPPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &quot;{0}&quot; has been extended from {1} to {2}.
        ///.
        /// </summary>
        internal static string EXTENDAPPROVED {
            get {
                return ResourceManager.GetString("EXTENDAPPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the leave request {0} has been approved from {1} to {2} by {3}.
        /// </summary>
        internal static string LEAVE_APPROVED_NOTIFICATION {
            get {
                return ResourceManager.GetString("LEAVE_APPROVED_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request {0} has been rejected for {1} by {2}.
        /// </summary>
        internal static string LEAVE_REJECTED_NOTIFICATION {
            get {
                return ResourceManager.GetString("LEAVE_REJECTED_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New leave request {0} from {1} start from {2} to {3}.
        /// </summary>
        internal static string LEAVEREQUESTCREATED {
            get {
                return ResourceManager.GetString("LEAVEREQUESTCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new task has been assigned to you: {0} number {1}.
        /// </summary>
        internal static string TASK_ASSIGNED_NOTIFICATION {
            get {
                return ResourceManager.GetString("TASK_ASSIGNED_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new close request on task: {0} from {1}.
        /// </summary>
        internal static string TASK_CLOSE_REQUEST_NOTIFICATION {
            get {
                return ResourceManager.GetString("TASK_CLOSE_REQUEST_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a new comment on task: {0} from {1}.
        /// </summary>
        internal static string TASK_COMMENT_NOTIFICATION {
            get {
                return ResourceManager.GetString("TASK_COMMENT_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new extension request on task: {0} from {1}.
        /// </summary>
        internal static string TASK_EXTENSION_REQUEST_NOTIFICATION {
            get {
                return ResourceManager.GetString("TASK_EXTENSION_REQUEST_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a new penalty on task: {0} from {1}.
        /// </summary>
        internal static string TASK_PENALTY_NOTIFICATION {
            get {
                return ResourceManager.GetString("TASK_PENALTY_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have been removed from {0}.
        /// </summary>
        internal static string TASK_UNASSIGNED_NOTIFICATION {
            get {
                return ResourceManager.GetString("TASK_UNASSIGNED_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning on task {0} from {1} .
        /// </summary>
        internal static string TASK_WARNING_NOTIFICATION {
            get {
                return ResourceManager.GetString("TASK_WARNING_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} achieved {1} from task: {2}.
        /// </summary>
        internal static string TASKACHIEVEMENT {
            get {
                return ResourceManager.GetString("TASKACHIEVEMENT", resourceCulture);
            }
        }
    }
}
