name: Build and deploy Hangfire to Azure Web App - taskmangment-hangfire

on:
  push:
    branches:
      - deploy_branch
    paths:
      - 'TaskMangmentHangfire/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # 👇 مهم: build المشروع نفسه
      - name: Build Hangfire project
        run: dotnet build TaskMangmentHangfire/TaskMangmentHangfire.csproj --configuration Release

      # 👇 publish لمجلد واضح
      - name: Publish Hangfire
        run: dotnet publish TaskMangmentHangfire/TaskMangmentHangfire.csproj -c Release -o ./publish

      # 👇 upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hangfire-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hangfire-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1593C7195C2A47D6BA0EA5314D46A245 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_97BE4FC9B7D04B5B9E101255C6DDB7C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3869A864C2F4A9C91EDEE4C5BA86F71 }}

      - name: Deploy Hangfire
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'taskmangment-hangfire'
          slot-name: 'Production'
          package: .
