name: Build and deploy API to Azure Web App - TaskMangmentApi

on:
  push:
    branches:
      - deploy_branch
    paths:
      - 'TaskMangmentApi/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # 👇 restore dependencies
      - name: Restore
        run: dotnet restore TaskMangmentApi/TaskMangmentApi.csproj

      # 👇 build المشروع نفسه فقط
      - name: Build API
        run: dotnet build TaskMangmentApi/TaskMangmentApi.csproj --configuration Release --no-restore

      # 👇 publish نظيف
      - name: Publish API
        run: dotnet publish TaskMangmentApi/TaskMangmentApi.csproj -c Release --no-build -o ./publish

      # 👇 upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app

      - name: Deploy API
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TaskMangmentApi'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_18A30A224F174CB498C1982D753B3BA4 }}
